AmericaVirtualChallengue.Web/Controllers/OrderController.cs
namespace AmericaVirtualChallengue.Web.Controllers
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Models.Data;
    using Models.Data.Repositories;
    using Models.ModelsView;

    [Authorize(Roles = "Admin, User")]
    public class OrdersController : Controller
    {
        private readonly IOrderRepository orderRepository;
        private readonly IProductRepository productRepository;
        private readonly Serilog.ILogger seriLogger;

        public OrdersController(
            IOrderRepository orderRepository,
            IProductRepository productRepository,
            Serilog.ILogger seriLogger)
        {
            this.orderRepository = orderRepository;
            this.productRepository = productRepository;
            this.seriLogger = seriLogger;
        }

        /// <summary>
        /// Index
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            System.Linq.IQueryable<Models.Data.Entities.Order> model = await orderRepository.GetOrdersAsync(this.User.Identity.Name);
            return View(model);
        }

        /// <summary>
        /// Details
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(int id)
        {
            if (!await orderRepository.ExistAsync(id))
            {
                return this.RedirectToAction("/Home/Error404");
            }

            OrderViewModel model = await orderRepository.GetOrderDetailAsync(id, this.User.Identity.Name);

            if (model == null)
            {
                return this.RedirectToAction("NotAuthorized", "Account");
            }

            return View(model);
        }

        /// <summary>
        /// Create
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Create()
        {
            System.Linq.IQueryable<Models.Data.Entities.OrderDetailTemp> model = await this.orderRepository.GetDetailTempsAsync(this.User.Identity.Name);
            return this.View(model);
        }

        /// <summary>
        /// AddProduct
        /// </summary>
        /// <returns></returns>
        public IActionResult AddProduct()
        {
            AddItemViewModel model = new AddItemViewModel
            {
                Quantity = 1,
                Products = this.productRepository.GetComboProducts()
            };

            return View(model);
        }

        /// <summary>
        /// POST: AddProduct to temp order
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> AddProduct(AddItemViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                await this.orderRepository.AddItemToOrderAsync(model, this.User.Identity.Name);
                return this.RedirectToAction("Create");
            }

            return this.View(model);
        }

        /// <summary>
        /// Delete item from temp order
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> DeleteItem(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await this.orderRepository.DeleteDetailTempAsync(id.Value);

            return this.RedirectToAction("Create");
        }

        /// <summary>
        /// Increase
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Increase(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await this.orderRepository.ModifyOrderDetailTempQuantityAsync(id.Value, 1);
            return this.RedirectToAction("Create");
        }

        /// <summary>
        /// Decrease
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Decrease(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await this.orderRepository.ModifyOrderDetailTempQuantityAsync(id.Value, -1);
            return this.RedirectToAction("Create");
        }

        /// <summary>
        /// ConfirmOrder
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> ConfirmOrder()
        {
            bool response = await this.orderRepository.ConfirmOrderAsync(this.User.Identity.Name);
            if (response)
            {
                return this.RedirectToAction("Index");
            }

            return this.RedirectToAction("Create");
        }

    }

}

AmericaVirtualChallengue.Web/Controllers/ProductsController.cs
namespace AmericaVirtualChallengue.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Threading.Tasks;
    using Helpers;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using Models.Data;
    using Models.Data.Entities;
    using Models.ModelsView;

    public class ProductsController : Controller
    {
        private readonly IProductRepository productRepository;

        public ProductsController(IProductRepository productRepository)
        {
            this.productRepository = productRepository;
        }

        /// <summary>
        /// GET: Products
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            //TODO: hidden disabled products
            return View(this.productRepository.GetAll().OrderBy(p => p.Name));
        }

        /// <summary>
        /// GET: Products/Details/{id}
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                //TODO: Complete the redirections of project
                return new NotFoundViewResult("ProductNotFound");
            }

            Product product = await this.productRepository.GetByIdAsync(id.Value);
            if (product == null)
            {
                return new NotFoundViewResult("ProductNotFound");
            }

            List<Topic> topics = this.productRepository.GetTopicsByProduct(product);

            ProductViewAPI pVApi = this.productRepository.ToProductViewAPI(product, topics);


            return View(pVApi);
        }

        /// <summary>
        /// GET: Products/Create
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// POST: Products/Create
        /// </summary>
        /// <param name="view"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductViewModel view)
        {
            if (ModelState.IsValid)
            {
                // Verify if user sent a photo
                string path = string.Empty;

                if (view.ImageFile != null && view.ImageFile.Length > 0)
                {
                    string guid = Guid.NewGuid().ToString();

                    path = Path.Combine(
                        Directory.GetCurrentDirectory(),
                        "wwwroot\\images\\Products",
                        $"{guid}{view.ImageFile.FileName}");

                    using (FileStream stream = new FileStream(path, FileMode.Create))
                    {
                        await view.ImageFile.CopyToAsync(stream);
                    }

                    path = $"~/images/Products/{guid}{view.ImageFile.FileName}";
                }

                // Create the Product object
                Product product = this.ToProduct(view, path);

                await this.productRepository.CreateAsync(product);
                
                return RedirectToAction(nameof(Index));
            }

            return View(view);
        }

        /// <summary>
        /// GET: Products/Edit/{id}
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Product product = await this.productRepository.GetByIdAsync(id.Value);

            if (product == null)
            {
                return NotFound();
            }

            //TODO: Include edit topics or remove it
            // Transform to ProductViewModel object
            ProductViewModel view = this.ToProductViewModel(product);
            //List<Topic> topics = this.productRepository.GetTopicsByProduct(product);

            //ProductViewAPI view = this.productRepository.ToProductViewAPI(product,topics);

            return View(view);
        }

        /// <summary>
        /// POST: Products/Edit/{id}
        /// </summary>
        /// <param name="view"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductViewModel view)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // Verify if user sent a photo
                    string path = view.ImageUrl;

                    if (view.ImageFile != null && view.ImageFile.Length > 0)
                    {
                        string guid = Guid.NewGuid().ToString();

                        path = Path.Combine(
                            Directory.GetCurrentDirectory(),
                            "wwwroot\\images\\Products",
                            $"{guid}{view.ImageFile.FileName}");

                        using (FileStream stream = new FileStream(path, FileMode.Create))
                        {
                            await view.ImageFile.CopyToAsync(stream);
                        }

                        path = $"~/images/Products/{guid}{view.ImageFile.FileName}";
                    }

                    // Transform to Product object
                    Product product = this.ToProduct(view, path);
                    await this.productRepository.UpdateAsync(product);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await this.productRepository.ExistAsync(view.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(view);
        }

        /// <summary>
        /// GET: Products/Delete/{id}
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Product product = await this.productRepository.GetByIdAsync(id.Value);

            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        /// <summary>
        /// POST: Products/Delete/{id}
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Product product = await this.productRepository.GetByIdAsync(id);
            try
            {
                await this.productRepository.DeleteAsync(product);

            }
            catch (Exception)
            {
                ModelState.AddModelError("Error", "You can not delete this object because it has related records");
                return View(product);
            }

            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// ToProduct
        /// </summary>
        /// <param name="view"></param>
        /// <param name="path"></param>
        /// <returns></returns>
        private Product ToProduct(ProductViewModel view, string path)
        {
            return new Product
            {
                Description = view.Description,
                Id = view.Id,
                ImageUrl = path,
                IsAvailabe = view.IsAvailabe,
                Name = view.Name,
                Price = view.Price
            };
        }

        /// <summary>
        /// ToProductViewModel
        /// </summary>
        /// <param name="product"></param>
        /// <returns></returns>
        private ProductViewModel ToProductViewModel(Product product)
        {
            return new ProductViewModel
            {
                Description = product.Description,
                Id = product.Id,
                ImageUrl = product.ImageUrl,
                IsAvailabe = product.IsAvailabe,
                Name = product.Name,
                Price = product.Price
            };
        }

        /// <summary>
        /// ProductNotFound
        /// </summary>
        /// <returns></returns>
        public IActionResult ProductNotFound()
        {
            return this.View();
        }

    }
}

AmericaVirtualChallengue.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AmericaVirtualChallengue.Web</title>
    <link rel="shortcut icon" href="~/images/logo.png" />

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/node_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
        <link href="~/node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link href="~/node_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
        <link href="~/node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AmericaVirtualChallenge</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Products" asp-action="Index">Products</a></li>
                    @if (this.User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Orders" asp-action="Index">Orders</a></li>
                        @if (this.User.IsInRole("Admin"))
                        {
                            <li><a asp-area="" asp-controller="Account" asp-action="Index">Users</a></li>
                        }
                    }

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (this.User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="ChangeUser">@this.User.Identity.Name</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a></li>
                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - AmericaVirtualChallenge</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>